### ISSUE TITLE
Is it possible to implement data filtering in training script?

### ISSUE THREAD

**Issue by vtddggg** [mlfoundations/datacomp#11]
**It seems the current process of data filtering is:** 
1. filtering `metadata.parquet` to get `sample_ids.npy` —> 2. reshard based on `sample_ids.npy` and save the new dataset again using `resharder.py`.

**But I think an ideal data filtering process will be:** 
1. filtering `data shards` to get `sample_ids.npy` because `data shards` contain more information such as image pixel value —> once `sample_ids.npy` is generated, the training script applies it for dataset construction directly. In this way, we need not to store data multiple times, which is time and storage consuming.

I know things will be different when data expands to billion level. There must be some reasons that you adopt the existing solution. 

But I still confuse if the second solution is possible or easy to implement? (at least for small track)

**Comment by vtddggg** [comment]
I got it. Thanks!

**Comment by vtddggg** [comment]
@gabrielilharco Sorry, I just reopen the issue again. 

When we want to compute clip score from raw image & text (instead of reading from `metadata `), we must learn to process `tars` files. However there are few reference examples about the use of webdatasets.

Regarding as the detailed implementation of baseline methods, can you provide a simple example about fetch uid & image & text data from `tars`, and generate `sample_ids.npy`? I think it will be very helpful

**Comment by gabrielilharco** [comment]
No problem! We also open-sourced code that we used for generating our metadata in this repo: https://github.com/mlfoundations/dataset2metadata. Let me know if that covers what you're looking for

**Comment by vtddggg** [comment]
Yes. Exactly it is what i am looking for!

By comparing the your uploaded [parquets](https://huggingface.co/datasets/mlfoundations/datacomp_pools) and my generated parquets using https://github.com/mlfoundations/dataset2metadata, I found there are some incompatible keys ('clip_b32_similarity_score' vs. 'oai-clip-vit-b32-score'). 

This problem I think can be solved by change `postprocess_parquet_lookup` (https://github.com/mlfoundations/dataset2metadata/blob/225408d90462323cf2afc5b40e789bc8cd966ce6/dataset2metadata/registry.py#L25)

I will post here once I finish my reproduction of baselines using this entire process.

**Comment by vtddggg** [comment]
> Yes. Exactly it is what i am looking for!
> 
> By comparing the your uploaded [parquets](https://huggingface.co/datasets/mlfoundations/datacomp_pools) and my generated parquets using https://github.com/mlfoundations/dataset2metadata, I found there are some incompatible keys ('clip_b32_similarity_score' vs. 'oai-clip-vit-b32-score').
> 
> This problem I think can be solved by change `postprocess_parquet_lookup` (https://github.com/mlfoundations/dataset2metadata/blob/225408d90462323cf2afc5b40e789bc8cd966ce6/dataset2metadata/registry.py#L25)
> 
> I will post here once I finish my reproduction of baselines using this entire process.

I ran `clip_score_l14_30_percent ` filtering on my generated parquets for small track, and got 5.39% zero-shot ImageNet acc, which is comparable with the official 5.1%.
