### ISSUE TITLE
reading images from within filtering script

### ISSUE THREAD

**Issue by nazMahmoud** [mlfoundations/datacomp#13]
I would like to be able to read images directly during the filtering step in `apply_filter.py`. I am able to get the url each image from the metadata. Instead of downloading each images, what the best way to get the image data from shards.

**Comment by vtddggg** [comment]
this issue https://github.com/mlfoundations/datacomp/issues/11 may help you

**Comment by gabrielilharco** [comment]
Hey @nazMahmoud, I agree with @vtddggg, probably the best way to generate metadata based on the images themselves is to do something like what we do here: https://github.com/mlfoundations/dataset2metadata
