### ISSUE TITLE
Error when creating the environment 

### ISSUE THREAD

**Issue by mamdouhJ** [mlfoundations/datacomp#14]
Hi everyone, 

When creating the environment, the package gcld3 cannot be installed. I am suspecting there is something to do with the Python version as the package can be installed with Python 3.6 up to 3.8 but Python 3.9 and newer have a problem with this package. 

This is the error message I'm getting: 

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gcld3

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I know this might not be the perfect place to raise this problem but the repo of the original package is not active. 

Thanks,

**Comment by sagadre** [comment]
Hi! Are you running: 

`conda env create --file environment.yml`?

Our default python version in the `environment.yml` is `3.10`. I just tried a clean install with the above command line and it installed ok.

If you are having problems with that command line let me know, and I can investigate further!

**Comment by mamdouhJ** [comment]
Thanks for the response, 

Yes, Im running the command as it is. I'm working on a remote server and have an old Conda version (4.10.x) which I couldn't upgrade for administrative reasons. Could that be the problem?

**Comment by mamdouhJ** [comment]
So far I have updated the Conda version to the latest and tried Mamba instead of Conda.  The error message has changed to 

`ERROR: Could not build wheels for gcld3, which is required to install pyproject.toml-based projects`

Thanks,

**Comment by mamdouhJ** [comment]
I have updated ubuntu from 16.04 to 18.04 and that solved the problem.

**Comment by meghbhalerao** [comment]
I was facing the same issue, I manually installed the necessary packages after creating the env and it worked.
