### ISSUE TITLE
Any plan to release the baseline checkpoints in the paper?

### ISSUE THREAD

**Issue by mingtan2** [mlfoundations/datacomp#15]
Hi the Team,

Is there any plan to release (some of) the checkpoints in the paper or leaderboard?

Thanks!

**Comment by gabrielilharco** [comment]
Hi @mingtan2. We released the main checkpoints as part of [OpenCLIP](https://github.com/mlfoundations/open_clip), see https://github.com/mlfoundations/open_clip/blob/main/docs/datacomp_models.md
