### ISSUE TITLE
Is there any evaluation randomness?

### ISSUE THREAD

**Issue by mingtan2** [mlfoundations/datacomp#18]
Hi the Team,

I tried to evaluate the model `commonpool_l_clip_s1b_b8k` [here](https://github.com/mlfoundations/open_clip/blob/main/docs/datacomp_models.md) using `evaluate.py`. The ImageNet acc1 is 0.57772, which is the same as 0.578 reported [here](https://github.com/mlfoundations/open_clip/blob/main/docs/datacomp_models.md), but the average result is 0.52936, which is different from 0.520 reported in Line `large/CLIP score (L/14 30%)` in Table 3 from your paper. Is this difference normal?

Thanks!

**Comment by sagadre** [comment]
Hi, thanks for the question! Our Flickr evaluation changed between the arxiv version and now. See this PR for the exact change: https://github.com/mlfoundations/datacomp/pull/12/files

We are in the process of updating the average numbers throughout the paper to be consistent with the updated evaluation code.
