### ISSUE TITLE
Problems evaluating trained model

### ISSUE THREAD

**Issue by mamdouhJ** [mlfoundations/datacomp#24]
Hi everyone, 

Im having trouble evaluating my trained model on the evaluation datasets. I downloaded the datasets but the evaluation script is only running my model on  the imagenet  1k dataset. I am running this command: 
`python evaluate.py --track filtering --data_dir ./eval_datasets/ --train_output_dir trained_models/clip_model_1`

Thanks for your time

**Comment by afang-story** [comment]
Hello, if you haven't pulled recently, you can add --submit to do the full eval
But you can also just pull the latest code, as this commit should have fixed this issue: https://github.com/mlfoundations/datacomp/commit/77d700c4078a541335efaa5a7c83ad52d3c11264
