### ISSUE TITLE
Leaderboard update

### ISSUE THREAD

**Issue by haichaoyu** [mlfoundations/datacomp#25]
Dear organizers, can I know when the leaderboard will be updated? It would be quite helpful to at least know some statistics about the leaderboard. Thanks.

**Comment by ch-shin** [comment]
Was there any follow-up on this? I am curious if the leaderboard will not be open until the end.

**Comment by ch-shin** [comment]
@gabrielilharco Thank you for your answer! Currently I can see datacomp team's submissions only (https://www.datacomp.ai/leaderboard.html)
![image](https://github.com/mlfoundations/datacomp/assets/28736511/f731471a-f3a5-4c0d-a9e6-b5f406aa896a)

So you mean, it will be updated soon, right? Thanks!

**Comment by gabrielilharco** [comment]
At the moment we only seem to have test submissions---despite some people working on it (e.g. https://arxiv.org/abs/2307.03132), no official submissions yet. If you submitted something and wish it was in the leaderboard, probably something went wrong, so please let us know!

**Comment by ch-shin** [comment]
Ah, I also submitted a baseline for testing and was thinking it's weird that nothing happened on the leaderboard. Thank you for the clarification!
But as far as I remember, I followed the submission instruction given on the README page. Are there any additional steps for official submissions? Or do we just need submission names looking official? 😇

**Comment by gabrielilharco** [comment]
I believe we received that one :)
No additional steps needed, just what's in the README

**Comment by ch-shin** [comment]
I see. Thank you for the clarification! I appreciate it.
