### ISSUE TITLE
Adding the detected_language to metadata 

### ISSUE THREAD

**Issue by fabiozappo** [mlfoundations/datacomp#26]
Hi! Thanks a lot for your work!

I can't find the detected_language column in the metadata, I suppose someone has to manually compute it and it in the parquet files but it takes quite a long time for a dataset like the xlarge pool. Having it stored in the metadata paruqet file would help all the people that have limited resources and want to prefilter the data before downloading the images.

Practical example:

I am interested in training a model only on the image-text pairs with english captions, and I that those data represent around the 30% of the small pool. Filtering out all the external languages would allow me to save a lot of storage space.

**Comment by sagadre** [comment]
Hi @fabiozappo we do not currently have plans of adding language tags to the metadata. However, I would suggest downloading only the metadata files using the `--skip_shards` flag as seen in the README. You could then run a modified version of [`basic_filtering`](https://github.com/mlfoundations/datacomp/blob/3ac587eefa16e57e4494f18024894fa642cd1a9f/baselines/apply_filter.py#L295) without the `in21k_mask` to get the desired tags uids for download.
