### ISSUE TITLE
Missing training file?

### ISSUE THREAD

**Issue by meghbhalerao** [mlfoundations/datacomp#32]
Dear Authors,
Thank you for the work and code. I was looking at the `train.py` file but here in this line - https://github.com/mlfoundations/datacomp/blob/main/train.py#L15 - it seems like the file/folder `training` seems to not be present in the GitHub repo?
Please let me know if I am missing anything, thank you!

**Comment by GeorgiosSmyrnis** [comment]
Hi @meghbhalerao!

The ```training``` module comes from ```open_clip```, and is installed as part of the corresponding package during the environment creation. You can find the module in the ```open_clip``` repository if you are interested in looking at the source code: https://github.com/mlfoundations/open_clip/tree/main/src/training.
