### ISSUE TITLE
train/test splits for downstream tasks

### ISSUE THREAD

**Issue by bluer555** [mlfoundations/datacomp#37]
Hello!

For some of the downstream datasets, the train-test splitting is unknown. Could you please share how the train and test subsets are split so that we can avoid using test images? The tasks with unknown train-test split are:
Caltech-101 [41], DTD [26], EuroSAT [57, 147], KITTI distance [44, 147], RESISC45 [23, 147], Dollar Street [115], GeoDE [107]

Thanks a lot!

**Comment by gabrielilharco** [comment]
Hey @bluer555, you can find all of the test sets here  https://huggingface.co/djghosh. E.g. for Caltech-101 see https://huggingface.co/datasets/djghosh/wds_vtab-caltech101_test. The datasets are in the webdataset format.
