### ISSUE TITLE
Result submission deadline

### ISSUE THREAD

**Issue by bluer555** [mlfoundations/datacomp#42]
Hello! I see the workshop paper submission deadline is September 8th, 2023. Is the result submission deadline (key list & model checkpoint submission) also the same day?

Thanks!

**Comment by gabrielilharco** [comment]
Hey @bluer555, we hope to keep datacomp as an ongoing competition even after the workshop, so we will continue to allow submissions after that deadline. At the workshop we'll show both the state of the leaderboard at the deadline and the current state of the leaderboard
