### ISSUE TITLE
How to precompute and save model-based metric during download?

### ISSUE THREAD

**Issue by bram-w** [mlfoundations/datacomp#52]
Hello, thanks for the work on this project! I was wondering if you had any example code/pointers for pre-computing model metrics during download. Specifically, we would like to have access to an aesthetic score (as in https://github.com/christophschuhmann/improved-aesthetic-predictor) when iterating through the dataset. I was looking at the filtering examples in `baselines/apply_filter.py` but those don't seem to cover computing a metric (on GPU) on the image after download and adding the result to the save file so it can be read w/o GPU compute at inference. Are there any relevant examples/templates? Thanks!

**Comment by gabrielilharco** [comment]
Hey @bram-w, check out https://github.com/mlfoundations/dataset2metadata. There are a few examples there of how to compute scores using trained models.

**Comment by bram-w** [comment]
That's exactly what I was looking for, thanks a ton!
