### ISSUE TITLE
Workshop submission deadline

### ISSUE THREAD

**Issue by mamdouhJ** [mlfoundations/datacomp#53]
Hi everyone, 

I am confused about the submission deadline. Is it by the end of the 8th of September or the end of the 7th of September? 
thanks

**Comment by gabrielilharco** [comment]
Hey @mamdouhJ, the deadline is Sep 8 AOE. Good luck with your submission!

**Comment by mamdouhJ** [comment]
Sorry for asking again.  Is the submission double-blind or should it be public? thanks

**Comment by gabrielilharco** [comment]
It's double blind
