### ISSUE TITLE
Conda environment build issue

### ISSUE THREAD

**Issue by brunnedu** [mlfoundations/datacomp#66]
Over the last couple days, I suddenly wasn't able to build the conda environment using `conda env create -f environment.yml` anymore and kept getting the attached error message. After following advice given in https://github.com/yaml/pyyaml/issues/724#issuecomment-1638587228 and changing the pyyaml requirement to `pyyaml==5.3.1` I was able to build the environment again. Not sure if this is a good permanent fix but I just wanted to raise awareness about this issue.

Error message:
> Collecting pyyaml==5.4.1
>   Using cached PyYAML-5.4.1.tar.gz (175 kB)
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'error'
> 
> Pip subprocess error:
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [62 lines of output]
>       /tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
>       !!
> 
>               ********************************************************************************
>               The license_file parameter is deprecated, use license_files instead.
> 
>               By 2023-Oct-30, you need to update your project and remove deprecated calls
>               or your builds will no longer be supported.
> 
>               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
>               ********************************************************************************
> 
>       !!
>         parsed = self.parsers.get(option_name, lambda x: x)(value)
>       running egg_info
>       writing lib3/PyYAML.egg-info/PKG-INFO
>       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
>       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
>       Traceback (most recent call last):
>         File "/itet-stor/brunnedu/net_scratch/conda_envs/datacomp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
>           main()
>         File "/itet-stor/brunnedu/net_scratch/conda_envs/datacomp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/itet-stor/brunnedu/net_scratch/conda_envs/datacomp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
>           exec(code, locals())
>         File "<string>", line 271, in <module>
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
>           return distutils.core.setup(**attrs)
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
>           return run_commands(dist)
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
>           dist.run_commands()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
>           super().run_command(command)
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 318, in run
>           self.find_sources()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
>           mm.run()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 548, in run
>           self.add_defaults()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
>           sdist.add_defaults(self)
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
>           super().add_defaults()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
>           self._add_defaults_ext()
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
>           self.filelist.extend(build_ext.get_source_files())
>         File "<string>", line 201, in get_source_files
>         File "/tmp/pip-build-env-7n51fsjq/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
>           raise AttributeError(attr)
>       AttributeError: cython_sources
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> failed
> 
> CondaEnvException: Pip failed

**Comment by gabrielilharco** [comment]
Thanks @brunnedu. I'm not able to reproduce this issue on my end, but good to know there's a fix in case others have the same issue

**Comment by adv010** [comment]
Thanks @brunnedu ! Ran into the same issue on Linux, this was helpful

**Comment by vanga** [comment]
@gabrielilharco do you think it will be useful to document this in the readme? or change the version to something that works?
I went through the same debugging as the OP where I landed upon that github issue of pyyaml suggesting to use 5.3.1 version.
