### ISSUE TITLE
Metadata for datacomp-large text-based filter

### ISSUE THREAD

**Issue by Viktour19** [mlfoundations/datacomp#72]
Great work with datacomp! Do you have the metadata for text-based filter of datacomp-large available to download? If not could you kindly consider uploading it.

**Comment by sagadre** [comment]
Hi @Viktour19, please see [here](https://github.com/mlfoundations/datacomp?tab=readme-ov-file#text-based-filtering) for code to reproduce the text-based filtering baseline
