### ISSUE TITLE
ModuleNotFoundError: No module named 'training'

### ISSUE THREAD

**Issue by adymaharana** [mlfoundations/datacomp#79]
Is this codebase missing a module called `training` or am I doing something weird? Asking because I ran this codebase several times last year and never faced an error until today when I cloned a fresh version from GitHub.

```
Traceback (most recent call last):
  File "/nas-ssd/adyasha/projects/datacomp/train.py", line 12, in <module>
    from training.distributed import world_info_from_env
ModuleNotFoundError: No module named 'training'
```

Any help is appreciated, thank you!

**Comment by sagadre** [comment]
hi @adymaharana! did you also install the virtual env from scratch? if not, maybe try that? `training` comes from `open_clip`, see here for more details: https://github.com/mlfoundations/datacomp/issues/32

**Comment by adymaharana** [comment]
Hi @sagadre ! So I _was_ doing something weird :) My virtual environment setup had errors and I didn't notice. Thanks for catching that.
