### ISSUE TITLE
How can I split the pool? I don't have a large enough storage for all

### ISSUE THREAD

**Issue by JianbangZ** [mlfoundations/datacomp#8]
ideally I want to split the pool to 2 separate harddrive, how to do it?

**Comment by gabrielilharco** [comment]
Hey @JianbangZ. You could split the parquet files into separate folders and call img2dataset separately for each folder

**Comment by JianbangZ** [comment]
> Hey @JianbangZ. You could split the parquet files into separate folders and call img2dataset separately for each folder

Good idea! Thanks
